### PR TITLE
Hmx hm phy setup

### PR DESCRIPTION
**Pull request by mattiasbus**

### CODE REVIEW

**Review by RikardO-HM — COMMENTED** [review]
How do i change modes? so one unit is master?

**Comment by mattiasbus** [comment]
> How do i change modes? so one unit is master?

It is currently hardcoded into the script, first phy is master

**Comment by RikardO-HM** [comment]
Then i need to cross the cables to get it to work?

**Comment by mattiasbus** [comment]
> Then i need to cross the cables to get it to work?

Yes, or change line:
phy.master = (i == 0) # set master on 1st phy
into 
phy.master = (i == 1) # set master on 2nd phy

**Pull request merged**
